# General settings
name: 'dev' # Warning: 'debug' and 'test' are reserved name that have a special behavior

parent_dir: '.'

wandb: 'online'             # online | offline | disabled
wandb_name: 'mass_spec_exp'
gpus: 1                     # Multi-gpu is not implemented on this branch


decoder: '../../../checkpoints/model_checkpoints/decoder.ckpt' # path to pretrained decoder
encoder: '../../../checkpoints/model_checkpoints/encoder_canopus.pt' # path to pretrained encoder

resume: null            # If resume, path to ckpt file from outputs direpctory in main directory
test_only: null

encoder_finetune_strategy: null  # null | freeze | ft-unfold | freeze-unfold | freeze-transformer | ft-transformer
decoder_finetune_strategy: null  # null | freeze | ft-input | freeze-input | ft-transformer | freeze-transformer | ft-output 

check_val_every_n_epochs: 1
sample_every_val: 10
val_samples_to_generate: 16      
test_samples_to_generate: 100
num_test_samples: 10000 # set to smaller number to evaluate on subset of test set    
log_every_steps: 50

evaluate_all_checkpoints: False
checkpoint_strategy: 'last'